### PR TITLE
Add support for CommonJs and UMD modules

### PR DESCRIPTION
**Pull request by nokome**
@christianp Thanks for creating `asciimath2tex` :pray:. We are using it in https://github.com/stencila/encoda for our [TeX codec](https://github.com/stencila/encoda/tree/master/src/codecs/tex).

Encoda is a Node.js package, so we needed support for CommonJs modules. This PR adds that support, thereby closing https://github.com/christianp/asciimath2tex/issues/5. It also adds support for UMD, which means the note about browser support in the README can be removed.

Other notes:

- if this is merged, `dist` should be `git rm`d before publishing; see https://github.com/christianp/asciimath2tex/commit/168f4bd7514c9161c39269283fbaa1fc6e3118c4

- if this is merged, you might want to add some docs on using via a `<script>` tag pointing to the UMD bundle on unpkg.com 

- I used `microbundle` instead of `babel` mainly because it is a lot quicker to configure.

### CODE REVIEW

**Comment by nokome** [comment]
:wave: @christianp Sorry to bother you, but just prodding to see if you could review this PR please.

**Comment by christianp** [comment]
Hi, sorry, I'm incredibly busy at the moment, I should have time to look at this in a couple of weeks. I've never used CommonJS or UMD, so I'll need to read up on how they work.

**Comment by christianp** [comment]
Thanks for this - I've merged this PR and updated the usage instructions. I'll look at how to publish a new version to npm later.

**Comment by nokome** [comment]
Thank you.

**Pull request merged**
